# Generated by Django 3.2.9 on 2022-04-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerJob', '0002_ofertaempleo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaempleo',
            name='UltimoDiaInscripcion',
            field=models.DateField(),
        ),
    ]
