# Generated by Django 3.2.9 on 2022-04-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerJob', '0007_alter_ofertaempleo_candidatos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaempleo',
            name='Candidatos',
            field=models.ManyToManyField(blank=True, to='seekerJob.Usuario'),
        ),
    ]
