# Generated by Django 3.2.9 on 2022-04-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekerJob', '0009_mensajes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mensajes',
        ),
    ]
