# Generated by Django 3.2.9 on 2022-05-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerJob', '0012_auto_20220430_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='anioNacimiento',
            field=models.DateField(help_text='Escriba una fecha posterior a una semana a partir del dia de hoy'),
        ),
    ]
