# Generated by Django 3.2.9 on 2022-05-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerJob', '0013_alter_usuario_anionacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaempleo',
            name='UltimoDiaInscripcion',
            field=models.DateField(help_text='Escriba una fecha posterior a una semana a partir del dia de hoy'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='anioNacimiento',
            field=models.DateField(),
        ),
    ]
