# Generated by Django 3.2.9 on 2022-05-13 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekerJob', '0015_estudiosminimos_jornadalaboral_presencialidad_puestodetrabajo_tipocontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaempleo',
            name='Presencialidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seekerJob.presencialidad'),
        ),
    ]
