# Generated by Django 3.2.9 on 2022-05-13 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekerJob', '0019_alter_ofertaempleo_presencialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaempleo',
            name='Presencialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekerJob.presencialidad'),
        ),
    ]
