# Generated by Django 3.2.9 on 2022-05-13 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekerJob', '0021_alter_ofertaempleo_presencialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertaempleo',
            name='Presencialidad',
        ),
        migrations.AddField(
            model_name='ofertaempleo',
            name='Presen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seekerJob.presencialidad'),
        ),
    ]
