# Generated by Django 3.2.9 on 2022-05-13 09:01

from django.db import migrations, models
import django.db.models.deletion
import seekerJob.models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerJob', '0023_alter_ofertaempleo_presen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaempleo',
            name='Presen',
            field=models.ForeignKey(default=seekerJob.models.JornadaLaboral, null=True, on_delete=django.db.models.deletion.CASCADE, to='seekerJob.presencialidad'),
        ),
    ]
