# Generated by Django 3.2.9 on 2022-05-13 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekerJob', '0024_alter_ofertaempleo_presen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertaempleo',
            name='Presen',
        ),
    ]
