# Generated by Django 3.2.9 on 2022-05-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekerJob', '0027_remove_ofertaempleo_presen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presencialidad',
        ),
    ]
