# Generated by Django 3.2.9 on 2022-05-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekerJob', '0029_presencialidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presencialidad',
            old_name='Trabajo',
            new_name='trabajo',
        ),
    ]
