# Generated by Django 3.2.9 on 2022-05-13 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekerJob', '0030_rename_trabajo_presencialidad_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaempleo',
            name='Presencialidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seekerJob.presencialidad'),
        ),
    ]
