# Generated by Django 3.2.9 on 2022-05-14 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekerJob', '0031_ofertaempleo_presencialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaempleo',
            name='Estudios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seekerJob.estudiosminimos'),
        ),
    ]
