# Generated by Django 3.2.9 on 2022-06-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerJob', '0036_titulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdiomaNiveles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=25)),
            ],
        ),
    ]
