# Generated by Django 3.2.9 on 2022-06-04 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekerJob', '0037_idiomaniveles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Idioma', models.CharField(max_length=25)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekerJob.usuario')),
                ('nivel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seekerJob.idiomaniveles')),
            ],
        ),
    ]
