# Generated by Django 3.2.9 on 2022-06-09 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekerJob', '0038_idiomas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Puesto', models.CharField(max_length=70)),
                ('FechaInicio', models.DateField()),
                ('FechaFin', models.DateField()),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekerJob.usuario')),
            ],
        ),
    ]
