# Generated by Django 3.2.9 on 2022-06-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerJob', '0039_experiencialaboral'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Foto',
            field=models.ImageField(default='user-default.png', upload_to='', verbose_name='Imagen de Perfil'),
        ),
    ]
