# Generated by Django 3.2.9 on 2022-06-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerJob', '0041_empresa_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialaboral',
            name='InstitucionEducativa',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='anioNacimiento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
