# Generated by Django 3.2.9 on 2022-06-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerJob', '0042_auto_20220618_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='InstitucionEducativa',
        ),
        migrations.AddField(
            model_name='titulos',
            name='InstitucionEducativa',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
