# Generated by Django 3.2.9 on 2022-06-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerJob', '0043_auto_20220618_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialaboral',
            name='Empresa',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
